# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_src',
            field=models.URLField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='nasa_id',
            field=models.IntegerField(unique=True),
        ),
    ]
