# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20160919_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasa_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('landing_date', models.DateField()),
                ('max_date', models.DateField()),
                ('max_sol', models.IntegerField()),
                ('total_photos', models.IntegerField()),
            ],
        ),
    ]
