# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_rover'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='next_photo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prev_photo', to='photos.Photo'),
            preserve_default=False,
        ),
    ]
