# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20160921_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rover',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='rover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='photos.Rover'),
        ),
    ]
