# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20160921_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='next_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_photo', to='photos.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='rover',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Rover'),
            preserve_default=False,
        ),
    ]
