# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20160921_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='camera',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.Camera'),
            preserve_default=False,
        ),
    ]
