# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0011_photo_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='next_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='prev_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_photo', to='photos.Photo'),
        ),
    ]
