# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20160921_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='concurrent',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
    ]
