# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_photo_concurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_null',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img_src',
            field=models.URLField(default='/static/img/null_rover.jpg', max_length=400),
        ),
    ]
