# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20160929_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='next_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='prev_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photos.Photo'),
        ),
    ]
